Repository abhilashmnair/aboutMe, pull requests merged in 2022-10, with the labels that each got.

#1 Added Initial README
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#3 Added Initial code
  data.json
  index.py
  templates/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#4 Added data access
  index.py
Labels: hacktoberfest, hacktoberfest-accepted

#5 Added RULES for making a pull request
  RULES.md
Labels: hacktoberfest, hacktoberfest-accepted

#6 Added Rules
  .gitattributes
  README.md
  RULES.md
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added data [username : abhishekmnair]
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#8 Added Documentation
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#9 Updated README documentation
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#10 Added LICENSE and fixed URLs
  LICENSE
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
